# Generated by Django 3.0.8 on 2020-08-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newcampaign_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcampaign',
            name='date',
            field=models.DateField(),
        ),
    ]
