# Generated by Django 3.0.8 on 2020-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200825_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaign',
            name='attendees',
            field=models.IntegerField(default=0),
        ),
    ]
