# Generated by Django 3.0.8 on 2020-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_newcampaign_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaign',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
